package pl.zmt.reader;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import pl.zmt.reader.entities.Compressor;
import pl.zmt.reader.entities.CompressorRepository;
import pl.zmt.reader.entities.User;
import pl.zmt.reader.entities.UserRepository;

@RestController
public class DatabaseClient {


    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    private UserRepository userRepository;

    @Autowired
    private CompressorRepository compressorRepository;

    @GetMapping("/users")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping("/compressors")
    public @ResponseBody
    Iterable<Compressor> getAllCompressors() {
        // This returns a JSON or XML with the compressors
        return compressorRepository.findAll();
    }


}
